apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_ADDR: "0.0.0.0:8080"
  GATEWAY_GRPC_ADDR: "0.0.0.0:"
  KAFKA_BROKERS: "kafka:9092"
  AUTH_SERVICE_ADDR: "auth-service:9090"
  USER_SERVICE_ADDR: "user-service:9091"
