apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  SRV_ENV: "development"
  AUTH_SRV_NAME: "auth-service"
  AUTH_SRV_PORT: "9090"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "auth_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_DB: "0"
  ACCESS_TOKEN_TTL: "15m"
  REFRESH_TOKEN_TTL: "168h"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SRV_ENV: "development"
  AUTH_SRV_NAME: "auth-service"
  AUTH_SRV_PORT: "9090"
  API_GATEWAY_PORT: "8080"