apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: ha-soranu
data:
  SRV_ENV: "development"
  AUTH_SRV_NAME: "auth-service"
  AUTH_SRV_PORT: "50051"
  POSTGRES_HOST: "pg-shared-rw.database"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "auth_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_DB: "0"
  ACCESS_TOKEN_TTL: "15m"
  REFRESH_TOKEN_TTL: "168h"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: ha-soranu
data:
  SRV_ENV: "development"
  AUTH_SRV_NAME: "auth-service"
  AUTH_SRV_PORT: "50051"
  API_GATEWAY_PORT: "8080"

  RESTAURANT_SRV_NAME: "restaurant-service"
  RESTAURANT_SRV_PORT: "50052"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-service-config
  namespace: ha-soranu
data:
  SRV_ENV: "development"
  RESTAURANT_SRV_NAME: "restaurant-service"
  RESTAURANT_SRV_PORT: "50052"
  POSTGRES_HOST: "pg-shared-rw.database"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "restaurant_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_DB: "1"
  KAFKA_BROKER_URL: "my-cluster-kafka-bootstrap.kafka:9092"
  RESTAURANT_SRV_CONSUMER_GROUP: "restaurant-service-group"
---